name: Build APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract project
        run: |
          unzip -q TegarJayaKeuangan_GitHubActions_Project.zip -d project

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build APK
        working-directory: project/TegarJayaKeuanganAndroid
        run: gradle :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TegarJayaKeuangan-debug-apk
          path: project/TegarJayaKeuanganAndroid/app/build/outputs/apk/debug/app-debug.apk
